# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94f1d38f6ef42f035cf175f89cafdd7c"
name = "Techies-Trust-badge"
application_url = "https://trust-badge-call-back-ptfk.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks/customers/redact"
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks/shop/redact"
api_version = "2025-10"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://trust-badge-call-back-ptfk.vercel.app/api/auth" ]
