# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a8efd194281bb81257029bf58d0f47fa"
name = "trust-badge"
application_url = "https://trust-badge-call-back-ptfk.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
